package main;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bara
 */
public class FormLogin extends javax.swing.JFrame {
        int xx, xy;
        
    /**
     * Creates new form form_login
     */
    public FormLogin() {
        AccessXML.readXML();
        initComponents();
    }
    
    void bersih(){
        Username.setText("Username");
        Password.setText("Password");
    }
    
    public static boolean isLogin = true;
    public static String usernameLogin = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Name_logo = new javax.swing.JLabel();
        bt_close = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        tombol_login = new javax.swing.JButton();
        bg_page = new javax.swing.JLabel();
        bg_page2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_customer_70px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 70, 70));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3916598.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, 140));

<<<<<<< HEAD:src/main/form_login.java
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
=======
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setToolTipText("Password");
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
>>>>>>> 1180c2591dfcea0d4bb77a49e2dbb042c2520077:src/main/FormLogin.java
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 40));

        Name_logo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Name_logo.setText("JARD.ID");
        getContentPane().add(Name_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        bt_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_20px.png"))); // NOI18N
        bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_closeMouseClicked(evt);
            }
        });
        getContentPane().add(bt_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username.setText("Username");
        Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 200, 40));

        tombol_login.setBackground(new java.awt.Color(102, 204, 255));
        tombol_login.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tombol_login.setForeground(new java.awt.Color(255, 255, 255));
        tombol_login.setText("LOGIN");
        tombol_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tombol_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_loginMouseClicked(evt);
            }
        });
        tombol_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_loginActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, 30));

        bg_page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eXp_Marketing_Center-removebg-preview.png"))); // NOI18N
        getContentPane().add(bg_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        bg_page2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thedinnerconcierge_1.jpeg"))); // NOI18N
        getContentPane().add(bg_page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 530, 610));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void bt_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseClicked
        dispose();
    }//GEN-LAST:event_bt_closeMouseClicked

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void tombol_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol_loginActionPerformed

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        String username=Username.getText();
        if(username.equals("Username")){
            Username.setText("");
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        String username=Username.getText();
        if(username.equals("")||username.equals("Username")){
            Username.setText("Username");
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void tombol_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_loginMouseClicked
        String username = Username.getText();
        String password = Password.getText();
        
        if(User.users.get(username).equals(password)){
            isLogin = true;
            usernameLogin = username;
            FrameUtama mainApp = new FrameUtama();
            mainApp.showPanelDashboard();
            mainApp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_tombol_loginMouseClicked

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        String pass=Password.getText();
        if(pass.equals("")||pass.equals("Password")){
            Password.setText("Password");
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        String pass=Password.getText();
        if(pass.equals("Password")){
            Password.setText("");
        }
    }//GEN-LAST:event_PasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name_logo;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel bg_page;
    private javax.swing.JLabel bg_page2;
    private javax.swing.JLabel bt_close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton tombol_login;
    // End of variables declaration//GEN-END:variables
}
