/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Element;
import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

/**
 *
 * @author ryanf
 */
public class PanelDashboard extends javax.swing.JLayeredPane {
    
    private static PanelDashboard panelDashboard = null;
    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        xml2app();
        welcome.setText("Selamat datang "+FormLogin.usernameLogin);
    }
    
    public static javax.swing.JLayeredPane getPanelDashboard() {
        if (panelDashboard == null) {
            panelDashboard = new PanelDashboard();
        }
        return panelDashboard;
    }
    
    public static PanelDashboard getDashboard() {
        if (panelDashboard == null) {
            panelDashboard = new PanelDashboard();
        }
        return panelDashboard;
    }
    
    public void setUangKas(int uang){
        kolomKas.setText(Integer.toString(uang));
        app2xml();
    }
    
    public int getUangKas(){
        return Integer.parseInt(kolomKas.getText());
    }
    
    public void setTotalTransaksi(int num){
        kolomJumlahTransaksi.setText(Integer.toString(num));
        app2xml();
    }
    
    public void incrementTotalTransaksi(){
        kolomJumlahTransaksi.setText(Integer.toString(Integer.parseInt(kolomJumlahTransaksi.getText())+1));
        app2xml();
    }
    
    public void xml2app(){
        try {            
            //baca data app
            File inputFile_appdata = new File("src\\main\\Data_app.xml");
            DocumentBuilderFactory dbFactory_appdata = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder_appdata = dbFactory_appdata.newDocumentBuilder();
            Document doc_appdata = dBuilder_appdata.parse(inputFile_appdata);
            doc_appdata.getDocumentElement().normalize();

            Element rootElement = doc_appdata.getDocumentElement();
            
            NodeList nodeList_appdata = rootElement.getChildNodes();
            for (int i = 0; i < nodeList_appdata.getLength(); i++) {
                if (nodeList_appdata.item(i).getNodeType() == org.w3c.dom.Node.ELEMENT_NODE) {
                    Element element = (Element) nodeList_appdata.item(i);
                    if(element.getNodeName().equals("uangkas")){kolomKas.setText(element.getTextContent());}
                    if(element.getNodeName().equals("jumlahtransaksi")){kolomJumlahTransaksi.setText(element.getTextContent());}
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void app2xml(){
        try {
            // Create a new DocumentBuilder
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.newDocument();

            // Create root element
            Element rootElement = doc.createElement("appdata");
            doc.appendChild(rootElement);

            // Create and append other elements as needed
            Element childElement1 = doc.createElement("uangkas");
            childElement1.setTextContent(kolomKas.getText());
            rootElement.appendChild(childElement1);

            Element childElement2 = doc.createElement("jumlahtransaksi");
            childElement2.setTextContent(kolomJumlahTransaksi.getText());
            rootElement.appendChild(childElement2);

            // Write the new XML content to the file
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(new File("src\\main\\Data_app.xml"));
            transformer.transform(source, result);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kolomKas = new javax.swing.JLabel();
        kolomJumlahTransaksi = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(847, 505));

        welcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        welcome.setText(" ");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("UANG KAS");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("TOTAL TRANSAKSI");

        kolomKas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kolomKas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kolomKas.setText(" ");

        kolomJumlahTransaksi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kolomJumlahTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kolomJumlahTransaksi.setText(" ");

        setLayer(welcome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(kolomKas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(kolomJumlahTransaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(kolomKas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(kolomJumlahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kolomKas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kolomJumlahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kolomJumlahTransaksi;
    private javax.swing.JLabel kolomKas;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
